# general

config-version = 2
start-at-login = true
auto-reload-config = true

## mouse cursor tracking
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']

## workspaces
persistent-workspaces = [
  "work",
  "movie",
  "docs",
  "family",
  "E",
  "kbd",
  "fashion",
  "H",
  "sns",
  "ctrl",
  "tmp1",
  "tmp2",
  "tmp3",
]

# key bindings

[mode.main.binding]
  # move workspace to next window
  ctrl-alt-h = 'move-workspace-to-monitor left'
  ctrl-alt-l = 'move-workspace-to-monitor right'
  # move focus+cursor to next window (左右のディスプレイで仕事する用)
  ctrl-alt-j = 'focus-monitor left'
  ctrl-alt-k = 'focus-monitor right'
  # toggle horizontal / vertical
  alt-slash = 'layout tiles horizontal vertical'
  # toggle folat / title
  alt-comma = 'layout accordion horizontal vertical'

  ## workspaces
  alt-1 = 'workspace work'
  alt-2 = 'workspace movie'
  alt-3 = 'workspace docs'
  alt-4 = 'workspace family'
  alt-5 = 'workspace E'
  alt-6 = 'workspace kbd'
  alt-7 = 'workspace fashion'
  alt-8 = 'workspace H'
  alt-9 = 'workspace sns'
  alt-0 = 'workspace ctrl'
  alt-z = 'workspace tmp1'
  alt-x = 'workspace tmp2'
  alt-c = 'workspace tmp3'
  alt-tab = 'workspace-back-and-forth'
  alt-shift-1 = 'move-node-to-workspace work'
  alt-shift-2 = 'move-node-to-workspace movie'
  alt-shift-3 = 'move-node-to-workspace docs'
  alt-shift-4 = 'move-node-to-workspace family'
  alt-shift-5 = 'move-node-to-workspace E'
  alt-shift-6 = 'move-node-to-workspace kbd'
  alt-shift-7 = 'move-node-to-workspace fashion'
  alt-shift-8 = 'move-node-to-workspace H'
  alt-shift-9 = 'move-node-to-workspace sns'
  alt-shift-0 = 'move-node-to-workspace ctrl'
  alt-shift-z = 'move-node-to-workspace tmp1'
  alt-shift-x = 'move-node-to-workspace tmp2'
  alt-shift-c = 'move-node-to-workspace tmp3'

  alt-h = 'focus --wrap-around left'
  alt-j = 'focus --wrap-around down'
  alt-k = 'focus --wrap-around up'
  alt-l = 'focus --wrap-around right'

  # re-org windows in same workspace
  alt-shift-h = 'move left'
  alt-shift-j = 'move down'
  alt-shift-k = 'move up'
  alt-shift-l = 'move right'

  # join (vertical + horizontal panel)
  alt-ctrl-left="join-with left"
  alt-ctrl-down="join-with down"
  alt-ctrl-up="join-with up"
  alt-ctrl-right="join-with right"
